export type Vec3=[number,number,number];
export interface Command{op:string;args:(string|number)[];line:number}
export interface Locator{name:string;kind:number;position:Vec3;source:string;heading?:number;interior?:string}
export type ObjectiveType='goto'|'getin'|'talkto'|'dialogue'|'interior'|'gooutside'|'race'|'follow'|'losetail'|'delivery'|'dump'|'destroy'|'pickupitem'|'destroyboss'|'timer'|'fmv'|'buycar'|'buyskin'|'coins';
export interface Condition{type:string;args:(string|number)[];commands:Command[]}
export interface Stage{index:number;args:(string|number)[];commands:Command[];objective:{type:ObjectiveType;mode:string};conditions:Condition[];checkpoint:boolean;message?:string;messageIndex?:number;icon?:string}
export interface Mission{id:string;level:number;title:string;setup:Command[];stages:Stage[];intro:Mission|null;load:Command[];introLoad:Command[];transition:boolean;optional?:boolean;source:string}
export interface Interior{name:string;scene:string;locators:Record<string,Locator>;start:Locator|null;exit:Locator|null}
export interface Chapter{id:number;endMovie?:string|null;missions:Mission[];initial:Command[];schedule:Command[];locators:Record<string,Locator>;interiors:Interior[]}
export interface Reward{id:string;path:string;type:'car'|'skin';quest:string;level:number;cost:number;seller:string}
export interface EntityState{id:string;position:Vec3;health:number;finished?:boolean;waypoint?:number;progress?:number;interior?:string}
export interface Snapshot{position:Vec3;onFoot:boolean;vehicle:string;health:number;interior:string|null;entities:Record<string,EntityState>;interact?:boolean;hitVehicle?:string;dialogueDone?:boolean;movieDone?:boolean;bossHit?:boolean;cargoLost?:boolean;parkedPosition?:Vec3;brokenCollectibles?:number[];collectibles?:Record<number,Vec3>}
export interface PlayerCheckpoint{position:Vec3;heading:number;onFoot:boolean;parkedPosition:Vec3;parkedHeading:number;vehicle:string;interior:string|null}
export interface Progress{version:2;level:number;mission:string;phase:'intro'|'main';stage:number;checkpoint:{phase:'intro'|'main';stage:number;remaining?:number|null;cargo?:string|null;player?:PlayerCheckpoint};story?:{mission:string;checkpoint:Progress['checkpoint']};completed:string[];money:number;cars:string[];skins:string[];equippedSkin:string|null;coins:Record<string,number[]>;brokenProps?:Record<string,string[]>;finished:boolean}
export type PrepareReason='new'|'load'|'checkpoint'|'advance'|'main';
export type Effect={type:'prepare';reason:PrepareReason;setup:Command[];commands:Command[];replay:Command[]}|{type:'stage-complete'|'mission-complete';title:string}|{type:'chapter-complete';nextLevel:number}|{type:'campaign-complete'}|{type:'failed';message:string}|{type:'purchase';reward:Reward}|{type:'collect';index:number}|{type:'drop';index:number;position:Vec3};
export const arg=(commands:Command[],op:string,fallback:(string|number)[]=[])=>(commands.find(c=>c.op===op)?.args??fallback);
export const all=(commands:Command[],op:string)=>commands.filter(c=>c.op===op).map(c=>c.args);
export const key=(value:unknown)=>String(value??'').toLowerCase();
export const distance=(a:Vec3,b:Vec3)=>Math.hypot(a[0]-b[0],a[1]-b[1],a[2]-b[2]);
export interface VoiceClip{line:number;actor:string;kind:string;file:string;mission:string}
/** Vehicle tuning and model tables. Loaded from campaign/assets.json — the mission scripts are gone, the tables are still what drives every car. */
export interface CampaignAssets{names:Record<string,string>;characters:Record<string,string>;cars:Record<string,string>;props:Record<string,string>;dialogue:Record<string,VoiceClip[]>;tuning:Record<string,Record<string,number>>;missionTuning:Record<string,Record<string,number>>;presentations:Record<string,string>}
