import * as THREE from 'three';
import {TrafficPath} from './traffic-path';
import {SteeringDriver} from './steering';
import type {World} from './world';
import type {Input} from './input';
import type {CarState,Controls} from './physics';
export interface Shot{id:string;title:string;level:number;car:string;seconds:number;position?:[number,number,number];heading?:number;speed?:number;location?:number;mission?:string;phase?:'intro'|'main';stage?:number;foot?:boolean;free?:boolean;objective?:boolean;light?:string;pursuit?:boolean;auto?:boolean;hud?:boolean;angle:[number,number];distance:[number,number];height:[number,number];steps?:[number,string][];camera:'follow'|'side'|'front';}
const shots:Shot[]=[
 {id:'fence-recovery-check',title:'QA / fence recovery',level:1,car:'famil_v',seconds:8,free:true,position:[180.5,4.1,204.5],heading:0,speed:3,hud:true,angle:[-.6,-.2],distance:[8,9],height:[3,4],camera:'follow',steps:[[0,'W'],[1.1,'SPACE'],[2.5,'S'],[7,'SPACE']]},
 {id:'waterfront-drive',title:'Lisa / waterfront run',level:3,car:'lisa_v',seconds:6,free:true,location:3,speed:18,auto:true,light:'golden',angle:[.35,.65],distance:[9,8],height:[2.5,3.2],camera:'front'},
 {id:'smithers-smash',title:'Hit and Run / ram Smithers',level:1,car:'famil_v',seconds:6,mission:'m3',stage:3,position:[220,3.5,161],heading:Math.PI/2,speed:25,hud:true,angle:[-.65,-.4],distance:[10,8],height:[2.5,3.0],camera:'follow',steps:[[0,'W'],[2,'W+A'],[2.8,'W'],[4,'SPACE']]},
 {id:'ramp',title:'Ramp jump / moving chase camera',level:1,car:'famil_v',seconds:6,free:true,position:[141.046,5.522,190.546],heading:0,speed:20,angle:[-.35,-.1],distance:[8,10],height:[2.5,4],camera:'front',steps:[[0,'W'],[2.5,''],[3.5,'SPACE']]},
 {id:'pursuit',title:'Police pursuit / rear tracking',level:1,car:'famil_v',seconds:8,free:true,position:[220,3.5,161],heading:Math.PI/2,speed:15,auto:true,pursuit:true,hud:true,angle:[.12,.42],distance:[13,11],height:[4.0,3.1],camera:'front'},
 {id:'skinner-race',title:'S-M-R-T / race Principal Skinner',level:1,car:'famil_v',seconds:8,mission:'m1',stage:2,speed:16,auto:true,hud:true,angle:[.35,.15],distance:[11,9],height:[3.2,3.5],camera:'follow'},
 {id:'crate',title:'Smash through the coin crate',level:1,car:'famil_v',seconds:5,free:true,position:[180.5,4.1,204.5],heading:0,speed:0,hud:true,angle:[.4,.1],distance:[8,9],height:[3.0,3.8],camera:'follow',steps:[[0,'W'],[1.1,'SPACE'],[2.5,'S'],[3.6,'SPACE']]},
 {id:'power-coupling',title:'Blind Big Brother / destroy the coupling',level:1,car:'famil_v',seconds:2,mission:'m4',stage:1,position:[-82.814,.06,-312.45],heading:Math.PI,foot:true,hud:true,angle:[-.35,.15],distance:[5.2,4.8],height:[1.65,2],camera:'follow',steps:[[0,'W'],[.18,'F'],[.55,'S']]},
 {id:'bart-escape',title:'Bart / evade Skinner downtown',level:2,car:'honor_v',seconds:8,mission:'m1',stage:2,speed:17,auto:true,hud:true,angle:[-.45,-.05],distance:[11,10],height:[3.1,3.6],camera:'follow'},
 {id:'haunted-pursuit',title:'Halloween / pursuit hearses',level:7,car:'homer_v',seconds:8,free:true,position:[220,3.5,161],heading:Math.PI/2,speed:16,auto:true,pursuit:true,hud:true,angle:[.2,-.25],distance:[14,11],height:[4.0,3.2],camera:'front'},
 {id:'ramp-reverse',title:'Ramp jump / side tracking',level:1,car:'famil_v',seconds:6,free:true,position:[141.046,5.522,190.546],heading:0,speed:20,angle:[-1.2,-.75],distance:[8,8],height:[1.8,2.7],camera:'side',steps:[[0,'W'],[2.5,''],[3.5,'SPACE']]},
];
interface Context{renderer:THREE.WebGLRenderer;camera:THREE.PerspectiveCamera;nativeHUD:{canvas:HTMLCanvasElement};input:Input;ready:()=>boolean;world:()=>World;player:()=>CarState;tuning:()=>Record<string,number>;info:()=>unknown;setup:(shot:Shot)=>Promise<void>;start:(shot:Shot)=>void;finish:()=>void;}
export function installDirector(c:Context){
 const panel=document.createElement('aside');panel.setAttribute('aria-label','Trailer director');panel.style.cssText='position:fixed;left:12px;bottom:12px;z-index:100;background:#111e;padding:12px;color:white;font:14px system-ui;max-width:95vw';
 const select=document.createElement('select');select.setAttribute('aria-label','Shot');for(const s of shots)select.add(new Option(s.title,s.id));const prepare=document.createElement('button'),record=document.createElement('button'),batch=document.createElement('button'),status=document.createElement('output');prepare.textContent='Prepare shot';record.textContent='Record shot';batch.textContent='Record all shots';record.disabled=true;status.textContent='Choose a shot';panel.append(select,prepare,record,batch,status);document.body.append(panel);
 const canvas=document.createElement('canvas');canvas.width=1920;canvas.height=1080;const ctx=canvas.getContext('2d')!;
 let active=false,recording=false,waiting=false,shot=shots[0],frame=0,path:TrafficPath|undefined,driver=new SteeringDriver(),stepIndex=-1,telemetry:unknown[]=[],done:(()=>void)|undefined;
 let startHeading=0,heading=0;const mix=(v:[number,number],t:number)=>THREE.MathUtils.lerp(v[0],v[1],t);
 async function prepareShot(){active=false;recording=false;record.disabled=true;prepare.disabled=true;status.textContent='Preparing…';shot=shots.find(s=>s.id===select.value)!;
  try{if(!c.ready())throw new Error('Wait for loading to finish');await c.setup(shot);path=undefined;const player=c.player();
   if(shot.auto){const roads=c.world().data.roads.map(r=>r.map(p=>new THREE.Vector3(...p as [number,number,number])));let best=Infinity,index=0,fraction=0;roads.forEach(([a,b],i)=>{const line=new THREE.Line3(a,b),f=line.closestPointToPointParameter(player.position,true),distance=line.at(f,new THREE.Vector3()).distanceToSquared(player.position);if(distance<best){best=distance;index=i;fraction=f;}});path=new TrafficPath(roads,index,false,fraction,c.world().data.navigation);player.heading=path.sample(player.position);const ground=c.world().terrain.ground(player.position.x,player.position.z,player.position.y,5);if(ground)player.position.y=ground.point.y+.06;}
   player.speed=0;frame=0;startHeading=heading=player.heading;stepIndex=-1;driver.reset();active=true;record.disabled=false;status.textContent=`Ready ${shot.id} · ${shot.seconds}s at 60 fps`;
  }catch(e){status.textContent=String(e);}finally{prepare.disabled=false;}
 }
 async function start(){if(!active)return;record.disabled=prepare.disabled=true;waiting=true;await fetch(`/__capture?shot=${shot.id}&frame=reset`,{method:'POST'});frame=0;stepIndex=-1;telemetry=[];c.start(shot);recording=true;waiting=false;status.textContent='Recording…';}
 prepare.onclick=()=>void prepareShot();record.onclick=()=>void start();batch.onclick=async()=>{batch.disabled=true;for(const s of shots){select.value=s.id;await prepareShot();if(!active)break;await new Promise<void>(async resolve=>{done=resolve;await start();});}batch.disabled=false;status.textContent='All shots complete';};
 return {get active(){return active;},get recording(){return recording;},get waiting(){return waiting;},
 input(){if(!recording)return;const index=shot.steps?.reduce((found,[time],index)=>frame/60>=time?index:found,-1)??-1;if(index===stepIndex)return;stepIndex=index;c.input.clear();const codes:Record<string,string>={W:'KeyW',A:'KeyA',S:'KeyS',D:'KeyD',E:'KeyE',F:'KeyF',SPACE:'Space',SHIFT:'ShiftLeft'};for(const key of (shot.steps?.[index]?.[1]??'').split('+'))if(codes[key]){c.input.keys.add(codes[key]);c.input.pressed.add(codes[key]);}},
 controls():Controls|null{if(!recording||!path)return null;const player=c.player();path.track(player.position);return driver.controls(player,path.peek(Math.max(9,Math.abs(player.speed)*.9)).position,shot.speed??16,1/60,c.tuning());},
 camera(){if(!active)return;const p=c.player(),u=Math.min(1,frame/(shot.seconds*60)),t=u*u*(3-2*u),target=p.position.clone().add(new THREE.Vector3(0,shot.foot?1:1.1,0));const turn=Math.atan2(Math.sin(p.heading-heading),Math.cos(p.heading-heading));heading+=turn*(recording?.09:1);const a=(shot.camera==='side'?startHeading:heading)+(shot.camera==='front'?0:Math.PI)+mix(shot.angle,t),distance=mix(shot.distance,t),position=new THREE.Vector3(target.x+Math.sin(a)*distance,target.y+mix(shot.height,t),target.z+Math.cos(a)*distance);const delta=position.clone().sub(target),hit=c.world().terrain.raycast(target,delta.clone().normalize(),delta.length());if(hit)position.copy(hit.point).addScaledVector(delta.normalize(),-.4);c.camera.position.copy(position);c.camera.lookAt(target);c.camera.fov=shot.foot?49:57;c.camera.updateProjectionMatrix();},
 async afterFrame(){if(!recording||waiting)return;waiting=true;try{ctx.drawImage(c.renderer.domElement,0,0,1920,1080);if(shot.hud)ctx.drawImage(c.nativeHUD.canvas,0,0,1920,1080);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Capture failed')),'image/jpeg',.94));const response=await fetch(`/__capture?shot=${shot.id}&frame=${String(frame).padStart(4,'0')}`,{method:'POST',body:blob});if(!response.ok)throw new Error(await response.text());telemetry.push(c.info());frame++;status.textContent=`Recording ${shot.id} · ${frame}/${shot.seconds*60}`;if(frame>=shot.seconds*60){await fetch(`/__capture?shot=${shot.id}&frame=telemetry`,{method:'POST',body:JSON.stringify({shot,sourceRevision:'__SOURCE_REVISION__',frames:telemetry})});recording=false;active=false;c.input.clear();record.disabled=true;prepare.disabled=false;c.finish();status.textContent=`Complete ${shot.id} · ${frame} frames`;done?.();done=undefined;}}catch(e){recording=false;status.textContent=String(e);record.disabled=prepare.disabled=false;done?.();done=undefined;}finally{waiting=false;}}
 };
}
